const friendlyNameData = {
  adjectives: [
    'Brave',
    'Clever',
    'Swift',
    'Mighty',
    'Gentle',
    'Cunning',
    'Loyal',
    'Fierce',
    'Bold',
    'Noble',
    'Agile',
    'Calm',
    'Daring',
    'Eager',
    'Fearless',
    'Graceful',
    'Happy',
    'Inventive',
    'Jolly',
    'Keen',
    'Lively',
    'Majestic',
    'Neat',
    'Optimistic',
    'Playful',
    'Quick',
    'Radiant',
    'Sincere',
    'Tactful',
    'Unique',
    'Vibrant',
    'Witty',
    'Zesty',
    'Ambitious',
    'Cheerful',
    'Determined',
    'Energetic',
    'Friendly',
    'Gleeful',
    'Humble',
    'Imaginative',
    'Joyful',
    'Kind',
    'Luminous',
    'Merry',
    'Nimble',
    'Observant',
    'Peppy',
    'Quirky',
    'Resilient',
    'Spirited',
    'Thoughtful',
    'Upbeat',
    'Vigilant',
    'Whimsical',
    'Zealous',
    'Charming',
    'Diligent',
    'Enthusiastic',
    'Fearless',
    'Gracious',
    'Harmonious',
    'Intelligent',
    'Jubilant',
    'Knowledgeable',
    'Lighthearted',
    'Motivated',
    'Nurturing',
    'Outgoing',
    'Persistent',
    'Quizzical',
    'Resourceful',
    'Steadfast',
    'Talented',
    'Uplifting',
    'Valiant',
    'Warmhearted',
    'Youthful',
    'Adventurous',
    'Breezy',
    'Carefree',
    'Devoted',
    'Empathetic',
    'Flourishing',
    'Gallant',
    'Honest',
    'Inspiring',
  ],
  animals: [
    'Tiger',
    'Eagle',
    'Wolf',
    'Panther',
    'Fox',
    'Hawk',
    'Lion',
    'Owl',
    'Bear',
    'Shark',
    'Cheetah',
    'Jaguar',
    'Falcon',
    'Dolphin',
    'Lynx',
    'Raven',
    'Bison',
    'Stallion',
    'Otter',
    'Hedgehog',
    'Peacock',
    'Raccoon',
    'Koala',
    'Badger',
    'Meerkat',
    'Viper',
    'Gorilla',
    'Leopard',
    'Cobra',
    'Orca',
    'Tortoise',
    'Lizard',
    'Penguin',
    'Kangaroo',
    'Armadillo',
    'Moose',
    'Gazelle',
    'Chameleon',
    'Wolverine',
    'Ocelot',
    'Octopus',
    'Salamander',
    'Sloth',
    'Porcupine',
    'Caracal',
    'Hyena',
    'Weasel',
    'Gannet',
    'Albatross',
    'Mandrill',
    'Narwhal',
    'Opossum',
    'Red Panda',
    'Tapir',
    'Walrus',
    'Echidna',
    'Vulture',
    'Wombat',
  ],
};

// Custom hash function (Fowler-Noll-Vo FNV-1a variant)
function hashString(str: string): number {
  let hash = 2166136261; // FNV offset basis
  for (let i = 0; i < str.length; i++) {
    hash ^= str.charCodeAt(i);
    hash *= 16777619; // FNV prime
    hash = hash >>> 0; // Convert to unsigned 32-bit
  }
  return hash;
}

export default function friendlyName(id: string) {
  const hash = hashString(id);
  // Spread out the values to avoid clustering
  const adjIndex = Math.abs(
    (hash ^ (hash >>> 5)) % friendlyNameData.adjectives.length,
  );
  const animalIndex = Math.abs(
    (hash ^ (hash >>> 7)) % friendlyNameData.animals.length,
  );

  return `${friendlyNameData.adjectives[adjIndex]} ${friendlyNameData.animals[animalIndex]}`;
}
